options:
  lidarr-user:
    type: string
    default: "lidarr"
    description: "The user and groups to install Lidarr under. These will be created automatically"
  port:
    type: int
    default: 8686 
    description: "Port for Lidarr"
  restore-config:
    type: boolean
    default: False
    description: "Restore a previous configuration from resource"
  proxy-port:
    type: int
    default: 443
    description: "Port to request for reverse proxy access"
  proxy-domain:
    type: string
    default: "lidarr"
    description: "Subdomain to request from reverse proxy"
  proxy-url:
    type: string
    default: "/lidarr"
    description: 'Urlbase for revrse proxy, must start with a "/"'
  proxy-group:
    type: string
    default: "lidarr"
    description: "The name of the backend this charm will use, this should be unique for deployment/reverseproxy. Lidarr is not designed to be run in HA with multiple units grouped"
